image: continuumio/miniconda3:latest

pages:
  stage: deploy
  tags:
  - ci.inria.fr
  script:
# install pinocchio
  - conda init bash
  - source ~/.bashrc    # <- !!!
  - conda env create -f env.yaml
  - conda activate pynocchio
# generate the site
  - cd docs
  - pip install -r requirements.txt
  - python3 -m sphinx.cmd.build -M html "source" "build" 
  - cp source/my_theme.css build/html/_static/css
  - mkdir public/
  - cp -r build/html/ ../public
  # - cd ..
  # - pip install pytest
  # - pip install coverage
  # - coverage run -m pytest tests/test.py
  # - coverage html
  # - cp -r htmlcov/ public
  artifacts:
    paths:
    - public
  only:
  - master


tests:
  stage: deploy
  tags:
  - ci.inria.fr
  script:
# install pinocchio
  - conda init bash
  - source ~/.bashrc    # <- !!!
  - conda env create -f env.yaml
  - conda activate pynocchio
# run tests
  - pip install . 
  - pip install pytest
  - pip install coverage
  - coverage run -m pytest tests/test.py
  artifacts:
    paths:
    - public
  only:
  - master
