image: python:3.6-slim

pages:
  stage: deploy
  tags:
  - ci.inria.fr
  script:
# install pinocchio
  - sudo apt install -qqy lsb-release gnupg2 curl
  - echo "deb [arch=amd64] http://robotpkg.openrobots.org/packages/debian/pub $(lsb_release -cs) robotpkg" | sudo tee /etc/apt/sources.list.d/robotpkg.list
  - curl http://robotpkg.openrobots.org/packages/debian/robotpkg.key | sudo apt-key add -
  - sudo apt update
  - sudo apt install -qqy robotpkg-py3*-pinocchio
  - export PATH=/opt/openrobots/bin:$PATH
  - export PKG_CONFIG_PATH=/opt/openrobots/lib/pkgconfig:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=/opt/openrobots/lib:$LD_LIBRARY_PATH
  - export PYTHONPATH=/opt/openrobots/lib/python3.10/site-packages:$PYTHONPATH # Adapt your desired python version here
  - export CMAKE_PREFIX_PATH=/opt/openrobots:$CMAKE_PREFIX_PATH
# generate the site
  - cd docs
  - pip install -r requirements.txt
  - python3 -m sphinx.cmd.build -M html "source" "build" 
  - cp source/my_theme.css build/html/_static/css
  - mkdir public/
  - cp -r build/html/ ../public
  # - cd ..
  # - pip install pytest
  # - pip install coverage
  # - coverage run -m pytest tests/test.py
  # - coverage html
  # - cp -r htmlcov/ public
  artifacts:
    paths:
    - public
  only:
  - master


tests:
  stage: deploy
  tags:
  - ci.inria.fr
  script:
# install pinocchio
  - sudo apt install -qqy lsb-release gnupg2 curl
  - echo "deb [arch=amd64] http://robotpkg.openrobots.org/packages/debian/pub $(lsb_release -cs) robotpkg" | sudo tee /etc/apt/sources.list.d/robotpkg.list
  - curl http://robotpkg.openrobots.org/packages/debian/robotpkg.key | sudo apt-key add -
  - sudo apt update
  - sudo apt install -qqy robotpkg-py3*-pinocchio
  - export PATH=/opt/openrobots/bin:$PATH
  - export PKG_CONFIG_PATH=/opt/openrobots/lib/pkgconfig:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=/opt/openrobots/lib:$LD_LIBRARY_PATH
  - export PYTHONPATH=/opt/openrobots/lib/python3.10/site-packages:$PYTHONPATH # Adapt your desired python version here
  - export CMAKE_PREFIX_PATH=/opt/openrobots:$CMAKE_PREFIX_PATH
# run tests
  - pip install . 
  - pip install pytest
  - pip install coverage
  - coverage run -m pytest tests/test.py
  artifacts:
    paths:
    - public
  only:
  - master
